/*
Chapar Customer API

API for interacting with the Chapar shipping service.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
)

// checks if the BulkHistoryEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkHistoryEvent{}

// BulkHistoryEvent struct for BulkHistoryEvent
type BulkHistoryEvent struct {
	Time *string `json:"time,omitempty"`
	Date *string `json:"date,omitempty"`
	Status *string `json:"status,omitempty"`
	StatusNote *string `json:"status_note,omitempty"`
	Tracking *string `json:"tracking,omitempty"`
	Reference *string `json:"reference,omitempty"`
}

// NewBulkHistoryEvent instantiates a new BulkHistoryEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkHistoryEvent() *BulkHistoryEvent {
	this := BulkHistoryEvent{}
	return &this
}

// NewBulkHistoryEventWithDefaults instantiates a new BulkHistoryEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkHistoryEventWithDefaults() *BulkHistoryEvent {
	this := BulkHistoryEvent{}
	return &this
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *BulkHistoryEvent) GetTime() string {
	if o == nil || IsNil(o.Time) {
		var ret string
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkHistoryEvent) GetTimeOk() (*string, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *BulkHistoryEvent) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given string and assigns it to the Time field.
func (o *BulkHistoryEvent) SetTime(v string) {
	o.Time = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *BulkHistoryEvent) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkHistoryEvent) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *BulkHistoryEvent) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *BulkHistoryEvent) SetDate(v string) {
	o.Date = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BulkHistoryEvent) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkHistoryEvent) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BulkHistoryEvent) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *BulkHistoryEvent) SetStatus(v string) {
	o.Status = &v
}

// GetStatusNote returns the StatusNote field value if set, zero value otherwise.
func (o *BulkHistoryEvent) GetStatusNote() string {
	if o == nil || IsNil(o.StatusNote) {
		var ret string
		return ret
	}
	return *o.StatusNote
}

// GetStatusNoteOk returns a tuple with the StatusNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkHistoryEvent) GetStatusNoteOk() (*string, bool) {
	if o == nil || IsNil(o.StatusNote) {
		return nil, false
	}
	return o.StatusNote, true
}

// HasStatusNote returns a boolean if a field has been set.
func (o *BulkHistoryEvent) HasStatusNote() bool {
	if o != nil && !IsNil(o.StatusNote) {
		return true
	}

	return false
}

// SetStatusNote gets a reference to the given string and assigns it to the StatusNote field.
func (o *BulkHistoryEvent) SetStatusNote(v string) {
	o.StatusNote = &v
}

// GetTracking returns the Tracking field value if set, zero value otherwise.
func (o *BulkHistoryEvent) GetTracking() string {
	if o == nil || IsNil(o.Tracking) {
		var ret string
		return ret
	}
	return *o.Tracking
}

// GetTrackingOk returns a tuple with the Tracking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkHistoryEvent) GetTrackingOk() (*string, bool) {
	if o == nil || IsNil(o.Tracking) {
		return nil, false
	}
	return o.Tracking, true
}

// HasTracking returns a boolean if a field has been set.
func (o *BulkHistoryEvent) HasTracking() bool {
	if o != nil && !IsNil(o.Tracking) {
		return true
	}

	return false
}

// SetTracking gets a reference to the given string and assigns it to the Tracking field.
func (o *BulkHistoryEvent) SetTracking(v string) {
	o.Tracking = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *BulkHistoryEvent) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkHistoryEvent) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *BulkHistoryEvent) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *BulkHistoryEvent) SetReference(v string) {
	o.Reference = &v
}

func (o BulkHistoryEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkHistoryEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusNote) {
		toSerialize["status_note"] = o.StatusNote
	}
	if !IsNil(o.Tracking) {
		toSerialize["tracking"] = o.Tracking
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	return toSerialize, nil
}

type NullableBulkHistoryEvent struct {
	value *BulkHistoryEvent
	isSet bool
}

func (v NullableBulkHistoryEvent) Get() *BulkHistoryEvent {
	return v.value
}

func (v *NullableBulkHistoryEvent) Set(val *BulkHistoryEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkHistoryEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkHistoryEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkHistoryEvent(val *BulkHistoryEvent) *NullableBulkHistoryEvent {
	return &NullableBulkHistoryEvent{value: val, isSet: true}
}

func (v NullableBulkHistoryEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkHistoryEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


