/*
Chapar Customer API

API for interacting with the Chapar shipping service. All requests are sent with a single query parameter `input` which contains a URL-encoded JSON string payload.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
)

// checks if the HistoryReportResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HistoryReportResponse{}

// HistoryReportResponse struct for HistoryReportResponse
type HistoryReportResponse struct {
	Cn *HistoryConsignmentNote `json:"cn,omitempty"`
	Receiver *HistoryContact `json:"receiver,omitempty"`
	Financial *Financial `json:"financial,omitempty"`
	History []HistoryItem `json:"history,omitempty"`
}

// NewHistoryReportResponse instantiates a new HistoryReportResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHistoryReportResponse() *HistoryReportResponse {
	this := HistoryReportResponse{}
	return &this
}

// NewHistoryReportResponseWithDefaults instantiates a new HistoryReportResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHistoryReportResponseWithDefaults() *HistoryReportResponse {
	this := HistoryReportResponse{}
	return &this
}

// GetCn returns the Cn field value if set, zero value otherwise.
func (o *HistoryReportResponse) GetCn() HistoryConsignmentNote {
	if o == nil || IsNil(o.Cn) {
		var ret HistoryConsignmentNote
		return ret
	}
	return *o.Cn
}

// GetCnOk returns a tuple with the Cn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryReportResponse) GetCnOk() (*HistoryConsignmentNote, bool) {
	if o == nil || IsNil(o.Cn) {
		return nil, false
	}
	return o.Cn, true
}

// HasCn returns a boolean if a field has been set.
func (o *HistoryReportResponse) HasCn() bool {
	if o != nil && !IsNil(o.Cn) {
		return true
	}

	return false
}

// SetCn gets a reference to the given HistoryConsignmentNote and assigns it to the Cn field.
func (o *HistoryReportResponse) SetCn(v HistoryConsignmentNote) {
	o.Cn = &v
}

// GetReceiver returns the Receiver field value if set, zero value otherwise.
func (o *HistoryReportResponse) GetReceiver() HistoryContact {
	if o == nil || IsNil(o.Receiver) {
		var ret HistoryContact
		return ret
	}
	return *o.Receiver
}

// GetReceiverOk returns a tuple with the Receiver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryReportResponse) GetReceiverOk() (*HistoryContact, bool) {
	if o == nil || IsNil(o.Receiver) {
		return nil, false
	}
	return o.Receiver, true
}

// HasReceiver returns a boolean if a field has been set.
func (o *HistoryReportResponse) HasReceiver() bool {
	if o != nil && !IsNil(o.Receiver) {
		return true
	}

	return false
}

// SetReceiver gets a reference to the given HistoryContact and assigns it to the Receiver field.
func (o *HistoryReportResponse) SetReceiver(v HistoryContact) {
	o.Receiver = &v
}

// GetFinancial returns the Financial field value if set, zero value otherwise.
func (o *HistoryReportResponse) GetFinancial() Financial {
	if o == nil || IsNil(o.Financial) {
		var ret Financial
		return ret
	}
	return *o.Financial
}

// GetFinancialOk returns a tuple with the Financial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryReportResponse) GetFinancialOk() (*Financial, bool) {
	if o == nil || IsNil(o.Financial) {
		return nil, false
	}
	return o.Financial, true
}

// HasFinancial returns a boolean if a field has been set.
func (o *HistoryReportResponse) HasFinancial() bool {
	if o != nil && !IsNil(o.Financial) {
		return true
	}

	return false
}

// SetFinancial gets a reference to the given Financial and assigns it to the Financial field.
func (o *HistoryReportResponse) SetFinancial(v Financial) {
	o.Financial = &v
}

// GetHistory returns the History field value if set, zero value otherwise.
func (o *HistoryReportResponse) GetHistory() []HistoryItem {
	if o == nil || IsNil(o.History) {
		var ret []HistoryItem
		return ret
	}
	return o.History
}

// GetHistoryOk returns a tuple with the History field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryReportResponse) GetHistoryOk() ([]HistoryItem, bool) {
	if o == nil || IsNil(o.History) {
		return nil, false
	}
	return o.History, true
}

// HasHistory returns a boolean if a field has been set.
func (o *HistoryReportResponse) HasHistory() bool {
	if o != nil && !IsNil(o.History) {
		return true
	}

	return false
}

// SetHistory gets a reference to the given []HistoryItem and assigns it to the History field.
func (o *HistoryReportResponse) SetHistory(v []HistoryItem) {
	o.History = v
}

func (o HistoryReportResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HistoryReportResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cn) {
		toSerialize["cn"] = o.Cn
	}
	if !IsNil(o.Receiver) {
		toSerialize["receiver"] = o.Receiver
	}
	if !IsNil(o.Financial) {
		toSerialize["financial"] = o.Financial
	}
	if !IsNil(o.History) {
		toSerialize["history"] = o.History
	}
	return toSerialize, nil
}

type NullableHistoryReportResponse struct {
	value *HistoryReportResponse
	isSet bool
}

func (v NullableHistoryReportResponse) Get() *HistoryReportResponse {
	return v.value
}

func (v *NullableHistoryReportResponse) Set(val *HistoryReportResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHistoryReportResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHistoryReportResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHistoryReportResponse(val *HistoryReportResponse) *NullableHistoryReportResponse {
	return &NullableHistoryReportResponse{value: val, isSet: true}
}

func (v NullableHistoryReportResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHistoryReportResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


