/*
Chapar Customer API

API for interacting with the Chapar shipping service. Note the unique request format: POST requests use a multipart/form-data body with a single field named \"input\" that contains a stringified JSON payload.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
)

// checks if the BulkHistoryReportObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkHistoryReportObject{}

// BulkHistoryReportObject struct for BulkHistoryReportObject
type BulkHistoryReportObject struct {
	History []BulkHistoryItem `json:"history,omitempty"`
}

// NewBulkHistoryReportObject instantiates a new BulkHistoryReportObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkHistoryReportObject() *BulkHistoryReportObject {
	this := BulkHistoryReportObject{}
	return &this
}

// NewBulkHistoryReportObjectWithDefaults instantiates a new BulkHistoryReportObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkHistoryReportObjectWithDefaults() *BulkHistoryReportObject {
	this := BulkHistoryReportObject{}
	return &this
}

// GetHistory returns the History field value if set, zero value otherwise.
func (o *BulkHistoryReportObject) GetHistory() []BulkHistoryItem {
	if o == nil || IsNil(o.History) {
		var ret []BulkHistoryItem
		return ret
	}
	return o.History
}

// GetHistoryOk returns a tuple with the History field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkHistoryReportObject) GetHistoryOk() ([]BulkHistoryItem, bool) {
	if o == nil || IsNil(o.History) {
		return nil, false
	}
	return o.History, true
}

// HasHistory returns a boolean if a field has been set.
func (o *BulkHistoryReportObject) HasHistory() bool {
	if o != nil && !IsNil(o.History) {
		return true
	}

	return false
}

// SetHistory gets a reference to the given []BulkHistoryItem and assigns it to the History field.
func (o *BulkHistoryReportObject) SetHistory(v []BulkHistoryItem) {
	o.History = v
}

func (o BulkHistoryReportObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkHistoryReportObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.History) {
		toSerialize["history"] = o.History
	}
	return toSerialize, nil
}

type NullableBulkHistoryReportObject struct {
	value *BulkHistoryReportObject
	isSet bool
}

func (v NullableBulkHistoryReportObject) Get() *BulkHistoryReportObject {
	return v.value
}

func (v *NullableBulkHistoryReportObject) Set(val *BulkHistoryReportObject) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkHistoryReportObject) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkHistoryReportObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkHistoryReportObject(val *BulkHistoryReportObject) *NullableBulkHistoryReportObject {
	return &NullableBulkHistoryReportObject{value: val, isSet: true}
}

func (v NullableBulkHistoryReportObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkHistoryReportObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


