/*
Chapar Customer API

API for interacting with the Chapar shipping service.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
)

// checks if the BulkHistoryReportRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkHistoryReportRequest{}

// BulkHistoryReportRequest struct for BulkHistoryReportRequest
type BulkHistoryReportRequest struct {
	User *User `json:"user,omitempty"`
	Bulk []string `json:"bulk,omitempty"`
}

// NewBulkHistoryReportRequest instantiates a new BulkHistoryReportRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkHistoryReportRequest() *BulkHistoryReportRequest {
	this := BulkHistoryReportRequest{}
	return &this
}

// NewBulkHistoryReportRequestWithDefaults instantiates a new BulkHistoryReportRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkHistoryReportRequestWithDefaults() *BulkHistoryReportRequest {
	this := BulkHistoryReportRequest{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *BulkHistoryReportRequest) GetUser() User {
	if o == nil || IsNil(o.User) {
		var ret User
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkHistoryReportRequest) GetUserOk() (*User, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *BulkHistoryReportRequest) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given User and assigns it to the User field.
func (o *BulkHistoryReportRequest) SetUser(v User) {
	o.User = &v
}

// GetBulk returns the Bulk field value if set, zero value otherwise.
func (o *BulkHistoryReportRequest) GetBulk() []string {
	if o == nil || IsNil(o.Bulk) {
		var ret []string
		return ret
	}
	return o.Bulk
}

// GetBulkOk returns a tuple with the Bulk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkHistoryReportRequest) GetBulkOk() ([]string, bool) {
	if o == nil || IsNil(o.Bulk) {
		return nil, false
	}
	return o.Bulk, true
}

// HasBulk returns a boolean if a field has been set.
func (o *BulkHistoryReportRequest) HasBulk() bool {
	if o != nil && !IsNil(o.Bulk) {
		return true
	}

	return false
}

// SetBulk gets a reference to the given []string and assigns it to the Bulk field.
func (o *BulkHistoryReportRequest) SetBulk(v []string) {
	o.Bulk = v
}

func (o BulkHistoryReportRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkHistoryReportRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Bulk) {
		toSerialize["bulk"] = o.Bulk
	}
	return toSerialize, nil
}

type NullableBulkHistoryReportRequest struct {
	value *BulkHistoryReportRequest
	isSet bool
}

func (v NullableBulkHistoryReportRequest) Get() *BulkHistoryReportRequest {
	return v.value
}

func (v *NullableBulkHistoryReportRequest) Set(val *BulkHistoryReportRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkHistoryReportRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkHistoryReportRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkHistoryReportRequest(val *BulkHistoryReportRequest) *NullableBulkHistoryReportRequest {
	return &NullableBulkHistoryReportRequest{value: val, isSet: true}
}

func (v NullableBulkHistoryReportRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkHistoryReportRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


