/*
Chapar Customer API

API for interacting with the Chapar shipping service. All POST requests use a unique `multipart/form-data` structure where the main payload is a JSON string inside a form field named `input`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
)

// checks if the FinancialInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FinancialInfo{}

// FinancialInfo struct for FinancialInfo
type FinancialInfo struct {
	DeliveryCharge *string `json:"delivery_charge,omitempty"`
	TotalCharge *int32 `json:"total_charge,omitempty"`
}

// NewFinancialInfo instantiates a new FinancialInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinancialInfo() *FinancialInfo {
	this := FinancialInfo{}
	return &this
}

// NewFinancialInfoWithDefaults instantiates a new FinancialInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFinancialInfoWithDefaults() *FinancialInfo {
	this := FinancialInfo{}
	return &this
}

// GetDeliveryCharge returns the DeliveryCharge field value if set, zero value otherwise.
func (o *FinancialInfo) GetDeliveryCharge() string {
	if o == nil || IsNil(o.DeliveryCharge) {
		var ret string
		return ret
	}
	return *o.DeliveryCharge
}

// GetDeliveryChargeOk returns a tuple with the DeliveryCharge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinancialInfo) GetDeliveryChargeOk() (*string, bool) {
	if o == nil || IsNil(o.DeliveryCharge) {
		return nil, false
	}
	return o.DeliveryCharge, true
}

// HasDeliveryCharge returns a boolean if a field has been set.
func (o *FinancialInfo) HasDeliveryCharge() bool {
	if o != nil && !IsNil(o.DeliveryCharge) {
		return true
	}

	return false
}

// SetDeliveryCharge gets a reference to the given string and assigns it to the DeliveryCharge field.
func (o *FinancialInfo) SetDeliveryCharge(v string) {
	o.DeliveryCharge = &v
}

// GetTotalCharge returns the TotalCharge field value if set, zero value otherwise.
func (o *FinancialInfo) GetTotalCharge() int32 {
	if o == nil || IsNil(o.TotalCharge) {
		var ret int32
		return ret
	}
	return *o.TotalCharge
}

// GetTotalChargeOk returns a tuple with the TotalCharge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinancialInfo) GetTotalChargeOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCharge) {
		return nil, false
	}
	return o.TotalCharge, true
}

// HasTotalCharge returns a boolean if a field has been set.
func (o *FinancialInfo) HasTotalCharge() bool {
	if o != nil && !IsNil(o.TotalCharge) {
		return true
	}

	return false
}

// SetTotalCharge gets a reference to the given int32 and assigns it to the TotalCharge field.
func (o *FinancialInfo) SetTotalCharge(v int32) {
	o.TotalCharge = &v
}

func (o FinancialInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FinancialInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeliveryCharge) {
		toSerialize["delivery_charge"] = o.DeliveryCharge
	}
	if !IsNil(o.TotalCharge) {
		toSerialize["total_charge"] = o.TotalCharge
	}
	return toSerialize, nil
}

type NullableFinancialInfo struct {
	value *FinancialInfo
	isSet bool
}

func (v NullableFinancialInfo) Get() *FinancialInfo {
	return v.value
}

func (v *NullableFinancialInfo) Set(val *FinancialInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableFinancialInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableFinancialInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinancialInfo(val *FinancialInfo) *NullableFinancialInfo {
	return &NullableFinancialInfo{value: val, isSet: true}
}

func (v NullableFinancialInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinancialInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


