/*
Chapar Customer API

API for interacting with the Chapar shipping service. All POST requests use a unique `multipart/form-data` structure where the main payload is a JSON string inside a form field named `input`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkHistoryReportObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkHistoryReportObject{}

// BulkHistoryReportObject struct for BulkHistoryReportObject
type BulkHistoryReportObject struct {
	History []BulkHistoryEvent `json:"history"`
}

type _BulkHistoryReportObject BulkHistoryReportObject

// NewBulkHistoryReportObject instantiates a new BulkHistoryReportObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkHistoryReportObject(history []BulkHistoryEvent) *BulkHistoryReportObject {
	this := BulkHistoryReportObject{}
	this.History = history
	return &this
}

// NewBulkHistoryReportObjectWithDefaults instantiates a new BulkHistoryReportObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkHistoryReportObjectWithDefaults() *BulkHistoryReportObject {
	this := BulkHistoryReportObject{}
	return &this
}

// GetHistory returns the History field value
func (o *BulkHistoryReportObject) GetHistory() []BulkHistoryEvent {
	if o == nil {
		var ret []BulkHistoryEvent
		return ret
	}

	return o.History
}

// GetHistoryOk returns a tuple with the History field value
// and a boolean to check if the value has been set.
func (o *BulkHistoryReportObject) GetHistoryOk() ([]BulkHistoryEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.History, true
}

// SetHistory sets field value
func (o *BulkHistoryReportObject) SetHistory(v []BulkHistoryEvent) {
	o.History = v
}

func (o BulkHistoryReportObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkHistoryReportObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["history"] = o.History
	return toSerialize, nil
}

func (o *BulkHistoryReportObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"history",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkHistoryReportObject := _BulkHistoryReportObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkHistoryReportObject)

	if err != nil {
		return err
	}

	*o = BulkHistoryReportObject(varBulkHistoryReportObject)

	return err
}

type NullableBulkHistoryReportObject struct {
	value *BulkHistoryReportObject
	isSet bool
}

func (v NullableBulkHistoryReportObject) Get() *BulkHistoryReportObject {
	return v.value
}

func (v *NullableBulkHistoryReportObject) Set(val *BulkHistoryReportObject) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkHistoryReportObject) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkHistoryReportObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkHistoryReportObject(val *BulkHistoryReportObject) *NullableBulkHistoryReportObject {
	return &NullableBulkHistoryReportObject{value: val, isSet: true}
}

func (v NullableBulkHistoryReportObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkHistoryReportObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


