/*
Chapar Customer API

API for interacting with the Chapar shipping service. All requests are sent with a single query parameter `input` which contains a URL-encoded JSON string payload.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
)

// checks if the BulkImportResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkImportResponse{}

// BulkImportResponse struct for BulkImportResponse
type BulkImportResponse struct {
	Result []BulkImportResult `json:"result,omitempty"`
}

// NewBulkImportResponse instantiates a new BulkImportResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkImportResponse() *BulkImportResponse {
	this := BulkImportResponse{}
	return &this
}

// NewBulkImportResponseWithDefaults instantiates a new BulkImportResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkImportResponseWithDefaults() *BulkImportResponse {
	this := BulkImportResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *BulkImportResponse) GetResult() []BulkImportResult {
	if o == nil || IsNil(o.Result) {
		var ret []BulkImportResult
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkImportResponse) GetResultOk() ([]BulkImportResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *BulkImportResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given []BulkImportResult and assigns it to the Result field.
func (o *BulkImportResponse) SetResult(v []BulkImportResult) {
	o.Result = v
}

func (o BulkImportResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkImportResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableBulkImportResponse struct {
	value *BulkImportResponse
	isSet bool
}

func (v NullableBulkImportResponse) Get() *BulkImportResponse {
	return v.value
}

func (v *NullableBulkImportResponse) Set(val *BulkImportResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkImportResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkImportResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkImportResponse(val *BulkImportResponse) *NullableBulkImportResponse {
	return &NullableBulkImportResponse{value: val, isSet: true}
}

func (v NullableBulkImportResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkImportResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


