/*
Chapar Customer API

API for interacting with the Chapar shipping service. Note the unique request format: POST requests use a multipart/form-data body with a single field named \"input\" that contains a stringified JSON payload.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
)

// checks if the QuoteObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteObject{}

// QuoteObject struct for QuoteObject
type QuoteObject struct {
	Order *QuoteObjectOrder `json:"order,omitempty"`
}

// NewQuoteObject instantiates a new QuoteObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteObject() *QuoteObject {
	this := QuoteObject{}
	return &this
}

// NewQuoteObjectWithDefaults instantiates a new QuoteObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteObjectWithDefaults() *QuoteObject {
	this := QuoteObject{}
	return &this
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *QuoteObject) GetOrder() QuoteObjectOrder {
	if o == nil || IsNil(o.Order) {
		var ret QuoteObjectOrder
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteObject) GetOrderOk() (*QuoteObjectOrder, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *QuoteObject) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given QuoteObjectOrder and assigns it to the Order field.
func (o *QuoteObject) SetOrder(v QuoteObjectOrder) {
	o.Order = &v
}

func (o QuoteObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	return toSerialize, nil
}

type NullableQuoteObject struct {
	value *QuoteObject
	isSet bool
}

func (v NullableQuoteObject) Get() *QuoteObject {
	return v.value
}

func (v *NullableQuoteObject) Set(val *QuoteObject) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteObject) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteObject(val *QuoteObject) *NullableQuoteObject {
	return &NullableQuoteObject{value: val, isSet: true}
}

func (v NullableQuoteObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


