/*
Chapar Customer API

API for interacting with the Chapar shipping service. All POST requests use a unique `multipart/form-data` structure where the main payload is a JSON string inside a form field named `input`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
)

// checks if the HistoryReportData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HistoryReportData{}

// HistoryReportData struct for HistoryReportData
type HistoryReportData struct {
	Cn *ConsignmentNote `json:"cn,omitempty"`
	Receiver *ReceiverInfo `json:"receiver,omitempty"`
	Financial *FinancialInfo `json:"financial,omitempty"`
	History []HistoryEvent `json:"history,omitempty"`
}

// NewHistoryReportData instantiates a new HistoryReportData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHistoryReportData() *HistoryReportData {
	this := HistoryReportData{}
	return &this
}

// NewHistoryReportDataWithDefaults instantiates a new HistoryReportData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHistoryReportDataWithDefaults() *HistoryReportData {
	this := HistoryReportData{}
	return &this
}

// GetCn returns the Cn field value if set, zero value otherwise.
func (o *HistoryReportData) GetCn() ConsignmentNote {
	if o == nil || IsNil(o.Cn) {
		var ret ConsignmentNote
		return ret
	}
	return *o.Cn
}

// GetCnOk returns a tuple with the Cn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryReportData) GetCnOk() (*ConsignmentNote, bool) {
	if o == nil || IsNil(o.Cn) {
		return nil, false
	}
	return o.Cn, true
}

// HasCn returns a boolean if a field has been set.
func (o *HistoryReportData) HasCn() bool {
	if o != nil && !IsNil(o.Cn) {
		return true
	}

	return false
}

// SetCn gets a reference to the given ConsignmentNote and assigns it to the Cn field.
func (o *HistoryReportData) SetCn(v ConsignmentNote) {
	o.Cn = &v
}

// GetReceiver returns the Receiver field value if set, zero value otherwise.
func (o *HistoryReportData) GetReceiver() ReceiverInfo {
	if o == nil || IsNil(o.Receiver) {
		var ret ReceiverInfo
		return ret
	}
	return *o.Receiver
}

// GetReceiverOk returns a tuple with the Receiver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryReportData) GetReceiverOk() (*ReceiverInfo, bool) {
	if o == nil || IsNil(o.Receiver) {
		return nil, false
	}
	return o.Receiver, true
}

// HasReceiver returns a boolean if a field has been set.
func (o *HistoryReportData) HasReceiver() bool {
	if o != nil && !IsNil(o.Receiver) {
		return true
	}

	return false
}

// SetReceiver gets a reference to the given ReceiverInfo and assigns it to the Receiver field.
func (o *HistoryReportData) SetReceiver(v ReceiverInfo) {
	o.Receiver = &v
}

// GetFinancial returns the Financial field value if set, zero value otherwise.
func (o *HistoryReportData) GetFinancial() FinancialInfo {
	if o == nil || IsNil(o.Financial) {
		var ret FinancialInfo
		return ret
	}
	return *o.Financial
}

// GetFinancialOk returns a tuple with the Financial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryReportData) GetFinancialOk() (*FinancialInfo, bool) {
	if o == nil || IsNil(o.Financial) {
		return nil, false
	}
	return o.Financial, true
}

// HasFinancial returns a boolean if a field has been set.
func (o *HistoryReportData) HasFinancial() bool {
	if o != nil && !IsNil(o.Financial) {
		return true
	}

	return false
}

// SetFinancial gets a reference to the given FinancialInfo and assigns it to the Financial field.
func (o *HistoryReportData) SetFinancial(v FinancialInfo) {
	o.Financial = &v
}

// GetHistory returns the History field value if set, zero value otherwise.
func (o *HistoryReportData) GetHistory() []HistoryEvent {
	if o == nil || IsNil(o.History) {
		var ret []HistoryEvent
		return ret
	}
	return o.History
}

// GetHistoryOk returns a tuple with the History field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistoryReportData) GetHistoryOk() ([]HistoryEvent, bool) {
	if o == nil || IsNil(o.History) {
		return nil, false
	}
	return o.History, true
}

// HasHistory returns a boolean if a field has been set.
func (o *HistoryReportData) HasHistory() bool {
	if o != nil && !IsNil(o.History) {
		return true
	}

	return false
}

// SetHistory gets a reference to the given []HistoryEvent and assigns it to the History field.
func (o *HistoryReportData) SetHistory(v []HistoryEvent) {
	o.History = v
}

func (o HistoryReportData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HistoryReportData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cn) {
		toSerialize["cn"] = o.Cn
	}
	if !IsNil(o.Receiver) {
		toSerialize["receiver"] = o.Receiver
	}
	if !IsNil(o.Financial) {
		toSerialize["financial"] = o.Financial
	}
	if !IsNil(o.History) {
		toSerialize["history"] = o.History
	}
	return toSerialize, nil
}

type NullableHistoryReportData struct {
	value *HistoryReportData
	isSet bool
}

func (v NullableHistoryReportData) Get() *HistoryReportData {
	return v.value
}

func (v *NullableHistoryReportData) Set(val *HistoryReportData) {
	v.value = val
	v.isSet = true
}

func (v NullableHistoryReportData) IsSet() bool {
	return v.isSet
}

func (v *NullableHistoryReportData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHistoryReportData(val *HistoryReportData) *NullableHistoryReportData {
	return &NullableHistoryReportData{value: val, isSet: true}
}

func (v NullableHistoryReportData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHistoryReportData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


