/*
Chapar Customer API

API for interacting with the Chapar shipping service. All POST requests use a unique `multipart/form-data` structure where the main payload is a JSON string inside a form field named `input`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QuoteObjects type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteObjects{}

// QuoteObjects struct for QuoteObjects
type QuoteObjects struct {
	Order QuoteOrderDetails `json:"order"`
}

type _QuoteObjects QuoteObjects

// NewQuoteObjects instantiates a new QuoteObjects object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteObjects(order QuoteOrderDetails) *QuoteObjects {
	this := QuoteObjects{}
	this.Order = order
	return &this
}

// NewQuoteObjectsWithDefaults instantiates a new QuoteObjects object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteObjectsWithDefaults() *QuoteObjects {
	this := QuoteObjects{}
	return &this
}

// GetOrder returns the Order field value
func (o *QuoteObjects) GetOrder() QuoteOrderDetails {
	if o == nil {
		var ret QuoteOrderDetails
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *QuoteObjects) GetOrderOk() (*QuoteOrderDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *QuoteObjects) SetOrder(v QuoteOrderDetails) {
	o.Order = v
}

func (o QuoteObjects) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteObjects) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["order"] = o.Order
	return toSerialize, nil
}

func (o *QuoteObjects) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"order",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuoteObjects := _QuoteObjects{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuoteObjects)

	if err != nil {
		return err
	}

	*o = QuoteObjects(varQuoteObjects)

	return err
}

type NullableQuoteObjects struct {
	value *QuoteObjects
	isSet bool
}

func (v NullableQuoteObjects) Get() *QuoteObjects {
	return v.value
}

func (v *NullableQuoteObjects) Set(val *QuoteObjects) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteObjects) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteObjects) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteObjects(val *QuoteObjects) *NullableQuoteObjects {
	return &NullableQuoteObjects{value: val, isSet: true}
}

func (v NullableQuoteObjects) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteObjects) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


