/*
Chapar Customer API

API for interacting with the Chapar shipping service. All POST requests use a unique `multipart/form-data` structure where the main payload is a JSON string inside a form field named `input`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetCityRequestInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCityRequestInput{}

// GetCityRequestInput The main payload for getting cities, to be sent as a stringified JSON in the 'input' field.
type GetCityRequestInput struct {
	State GetCityRequestInputState `json:"state"`
}

type _GetCityRequestInput GetCityRequestInput

// NewGetCityRequestInput instantiates a new GetCityRequestInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCityRequestInput(state GetCityRequestInputState) *GetCityRequestInput {
	this := GetCityRequestInput{}
	this.State = state
	return &this
}

// NewGetCityRequestInputWithDefaults instantiates a new GetCityRequestInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCityRequestInputWithDefaults() *GetCityRequestInput {
	this := GetCityRequestInput{}
	return &this
}

// GetState returns the State field value
func (o *GetCityRequestInput) GetState() GetCityRequestInputState {
	if o == nil {
		var ret GetCityRequestInputState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *GetCityRequestInput) GetStateOk() (*GetCityRequestInputState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *GetCityRequestInput) SetState(v GetCityRequestInputState) {
	o.State = v
}

func (o GetCityRequestInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCityRequestInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *GetCityRequestInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCityRequestInput := _GetCityRequestInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetCityRequestInput)

	if err != nil {
		return err
	}

	*o = GetCityRequestInput(varGetCityRequestInput)

	return err
}

type NullableGetCityRequestInput struct {
	value *GetCityRequestInput
	isSet bool
}

func (v NullableGetCityRequestInput) Get() *GetCityRequestInput {
	return v.value
}

func (v *NullableGetCityRequestInput) Set(val *GetCityRequestInput) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCityRequestInput) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCityRequestInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCityRequestInput(val *GetCityRequestInput) *NullableGetCityRequestInput {
	return &NullableGetCityRequestInput{value: val, isSet: true}
}

func (v NullableGetCityRequestInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCityRequestInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


