/*
Chapar Customer API

API for interacting with the Chapar shipping service. All POST requests use a unique `multipart/form-data` structure where the main payload is a JSON string inside a form field named `input`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkHistoryReportRequestInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkHistoryReportRequestInput{}

// BulkHistoryReportRequestInput The main payload for bulk history report, to be sent as a stringified JSON in the 'input' field.
type BulkHistoryReportRequestInput struct {
	User User `json:"user"`
	Bulk []string `json:"bulk"`
}

type _BulkHistoryReportRequestInput BulkHistoryReportRequestInput

// NewBulkHistoryReportRequestInput instantiates a new BulkHistoryReportRequestInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkHistoryReportRequestInput(user User, bulk []string) *BulkHistoryReportRequestInput {
	this := BulkHistoryReportRequestInput{}
	this.User = user
	this.Bulk = bulk
	return &this
}

// NewBulkHistoryReportRequestInputWithDefaults instantiates a new BulkHistoryReportRequestInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkHistoryReportRequestInputWithDefaults() *BulkHistoryReportRequestInput {
	this := BulkHistoryReportRequestInput{}
	return &this
}

// GetUser returns the User field value
func (o *BulkHistoryReportRequestInput) GetUser() User {
	if o == nil {
		var ret User
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *BulkHistoryReportRequestInput) GetUserOk() (*User, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *BulkHistoryReportRequestInput) SetUser(v User) {
	o.User = v
}

// GetBulk returns the Bulk field value
func (o *BulkHistoryReportRequestInput) GetBulk() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Bulk
}

// GetBulkOk returns a tuple with the Bulk field value
// and a boolean to check if the value has been set.
func (o *BulkHistoryReportRequestInput) GetBulkOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bulk, true
}

// SetBulk sets field value
func (o *BulkHistoryReportRequestInput) SetBulk(v []string) {
	o.Bulk = v
}

func (o BulkHistoryReportRequestInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkHistoryReportRequestInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user"] = o.User
	toSerialize["bulk"] = o.Bulk
	return toSerialize, nil
}

func (o *BulkHistoryReportRequestInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user",
		"bulk",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkHistoryReportRequestInput := _BulkHistoryReportRequestInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkHistoryReportRequestInput)

	if err != nil {
		return err
	}

	*o = BulkHistoryReportRequestInput(varBulkHistoryReportRequestInput)

	return err
}

type NullableBulkHistoryReportRequestInput struct {
	value *BulkHistoryReportRequestInput
	isSet bool
}

func (v NullableBulkHistoryReportRequestInput) Get() *BulkHistoryReportRequestInput {
	return v.value
}

func (v *NullableBulkHistoryReportRequestInput) Set(val *BulkHistoryReportRequestInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkHistoryReportRequestInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkHistoryReportRequestInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkHistoryReportRequestInput(val *BulkHistoryReportRequestInput) *NullableBulkHistoryReportRequestInput {
	return &NullableBulkHistoryReportRequestInput{value: val, isSet: true}
}

func (v NullableBulkHistoryReportRequestInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkHistoryReportRequestInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


