/*
Chapar Customer API

API for interacting with the Chapar shipping service. All POST requests use a unique `multipart/form-data` structure where the main payload is a JSON string inside a form field named `input`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
)

// checks if the GetCityPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCityPost200Response{}

// GetCityPost200Response struct for GetCityPost200Response
type GetCityPost200Response struct {
	Success *bool `json:"success,omitempty"`
	Data *GetCityData `json:"data,omitempty"`
	Message NullableString `json:"message,omitempty"`
}

// NewGetCityPost200Response instantiates a new GetCityPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCityPost200Response() *GetCityPost200Response {
	this := GetCityPost200Response{}
	return &this
}

// NewGetCityPost200ResponseWithDefaults instantiates a new GetCityPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCityPost200ResponseWithDefaults() *GetCityPost200Response {
	this := GetCityPost200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetCityPost200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCityPost200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetCityPost200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetCityPost200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetCityPost200Response) GetData() GetCityData {
	if o == nil || IsNil(o.Data) {
		var ret GetCityData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCityPost200Response) GetDataOk() (*GetCityData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetCityPost200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GetCityData and assigns it to the Data field.
func (o *GetCityPost200Response) SetData(v GetCityData) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCityPost200Response) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCityPost200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *GetCityPost200Response) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *GetCityPost200Response) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *GetCityPost200Response) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *GetCityPost200Response) UnsetMessage() {
	o.Message.Unset()
}

func (o GetCityPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCityPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	return toSerialize, nil
}

type NullableGetCityPost200Response struct {
	value *GetCityPost200Response
	isSet bool
}

func (v NullableGetCityPost200Response) Get() *GetCityPost200Response {
	return v.value
}

func (v *NullableGetCityPost200Response) Set(val *GetCityPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCityPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCityPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCityPost200Response(val *GetCityPost200Response) *NullableGetCityPost200Response {
	return &NullableGetCityPost200Response{value: val, isSet: true}
}

func (v NullableGetCityPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCityPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


