/*
Chapar Customer API

API for interacting with the Chapar shipping service. All POST requests use a unique `multipart/form-data` structure where the main payload is a JSON string inside a form field named `input`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrackingRequestInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrackingRequestInput{}

// TrackingRequestInput The main payload for tracking, to be sent as a stringified JSON in the 'input' field.
type TrackingRequestInput struct {
	Order TrackingRequestInputOrder `json:"order"`
}

type _TrackingRequestInput TrackingRequestInput

// NewTrackingRequestInput instantiates a new TrackingRequestInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrackingRequestInput(order TrackingRequestInputOrder) *TrackingRequestInput {
	this := TrackingRequestInput{}
	this.Order = order
	return &this
}

// NewTrackingRequestInputWithDefaults instantiates a new TrackingRequestInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrackingRequestInputWithDefaults() *TrackingRequestInput {
	this := TrackingRequestInput{}
	return &this
}

// GetOrder returns the Order field value
func (o *TrackingRequestInput) GetOrder() TrackingRequestInputOrder {
	if o == nil {
		var ret TrackingRequestInputOrder
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *TrackingRequestInput) GetOrderOk() (*TrackingRequestInputOrder, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *TrackingRequestInput) SetOrder(v TrackingRequestInputOrder) {
	o.Order = v
}

func (o TrackingRequestInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrackingRequestInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["order"] = o.Order
	return toSerialize, nil
}

func (o *TrackingRequestInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"order",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrackingRequestInput := _TrackingRequestInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrackingRequestInput)

	if err != nil {
		return err
	}

	*o = TrackingRequestInput(varTrackingRequestInput)

	return err
}

type NullableTrackingRequestInput struct {
	value *TrackingRequestInput
	isSet bool
}

func (v NullableTrackingRequestInput) Get() *TrackingRequestInput {
	return v.value
}

func (v *NullableTrackingRequestInput) Set(val *TrackingRequestInput) {
	v.value = val
	v.isSet = true
}

func (v NullableTrackingRequestInput) IsSet() bool {
	return v.isSet
}

func (v *NullableTrackingRequestInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrackingRequestInput(val *TrackingRequestInput) *NullableTrackingRequestInput {
	return &NullableTrackingRequestInput{value: val, isSet: true}
}

func (v NullableTrackingRequestInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrackingRequestInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


