/*
Chapar Customer API

API for interacting with the Chapar shipping service. All POST requests use a unique `multipart/form-data` structure where the main payload is a JSON string inside a form field named `input`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QuoteRequestInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteRequestInput{}

// QuoteRequestInput The main payload, which will be stringified and sent as the 'input' form field.
type QuoteRequestInput struct {
	Order OrderDetails `json:"order"`
}

type _QuoteRequestInput QuoteRequestInput

// NewQuoteRequestInput instantiates a new QuoteRequestInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteRequestInput(order OrderDetails) *QuoteRequestInput {
	this := QuoteRequestInput{}
	this.Order = order
	return &this
}

// NewQuoteRequestInputWithDefaults instantiates a new QuoteRequestInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteRequestInputWithDefaults() *QuoteRequestInput {
	this := QuoteRequestInput{}
	return &this
}

// GetOrder returns the Order field value
func (o *QuoteRequestInput) GetOrder() OrderDetails {
	if o == nil {
		var ret OrderDetails
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *QuoteRequestInput) GetOrderOk() (*OrderDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *QuoteRequestInput) SetOrder(v OrderDetails) {
	o.Order = v
}

func (o QuoteRequestInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteRequestInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["order"] = o.Order
	return toSerialize, nil
}

func (o *QuoteRequestInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"order",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuoteRequestInput := _QuoteRequestInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuoteRequestInput)

	if err != nil {
		return err
	}

	*o = QuoteRequestInput(varQuoteRequestInput)

	return err
}

type NullableQuoteRequestInput struct {
	value *QuoteRequestInput
	isSet bool
}

func (v NullableQuoteRequestInput) Get() *QuoteRequestInput {
	return v.value
}

func (v *NullableQuoteRequestInput) Set(val *QuoteRequestInput) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteRequestInput) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteRequestInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteRequestInput(val *QuoteRequestInput) *NullableQuoteRequestInput {
	return &NullableQuoteRequestInput{value: val, isSet: true}
}

func (v NullableQuoteRequestInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteRequestInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


