/*
Chapar Customer API

API for interacting with the Chapar shipping service. Note the unique request format: POST requests use a multipart/form-data body with a single field named \"input\" that contains a stringified JSON payload.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package chapar

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkImportResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkImportResponse{}

// BulkImportResponse struct for BulkImportResponse
type BulkImportResponse struct {
	Result bool `json:"result"`
	Message NullableString `json:"message,omitempty"`
	Object BulkImportObject `json:"object"`
}

type _BulkImportResponse BulkImportResponse

// NewBulkImportResponse instantiates a new BulkImportResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkImportResponse(result bool, object BulkImportObject) *BulkImportResponse {
	this := BulkImportResponse{}
	this.Result = result
	this.Object = object
	return &this
}

// NewBulkImportResponseWithDefaults instantiates a new BulkImportResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkImportResponseWithDefaults() *BulkImportResponse {
	this := BulkImportResponse{}
	return &this
}

// GetResult returns the Result field value
func (o *BulkImportResponse) GetResult() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *BulkImportResponse) GetResultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *BulkImportResponse) SetResult(v bool) {
	o.Result = v
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkImportResponse) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkImportResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *BulkImportResponse) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *BulkImportResponse) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *BulkImportResponse) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *BulkImportResponse) UnsetMessage() {
	o.Message.Unset()
}

// GetObject returns the Object field value
func (o *BulkImportResponse) GetObject() BulkImportObject {
	if o == nil {
		var ret BulkImportObject
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *BulkImportResponse) GetObjectOk() (*BulkImportObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *BulkImportResponse) SetObject(v BulkImportObject) {
	o.Object = v
}

func (o BulkImportResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkImportResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	toSerialize["object"] = o.Object
	return toSerialize, nil
}

func (o *BulkImportResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
		"object",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkImportResponse := _BulkImportResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkImportResponse)

	if err != nil {
		return err
	}

	*o = BulkImportResponse(varBulkImportResponse)

	return err
}

type NullableBulkImportResponse struct {
	value *BulkImportResponse
	isSet bool
}

func (v NullableBulkImportResponse) Get() *BulkImportResponse {
	return v.value
}

func (v *NullableBulkImportResponse) Set(val *BulkImportResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkImportResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkImportResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkImportResponse(val *BulkImportResponse) *NullableBulkImportResponse {
	return &NullableBulkImportResponse{value: val, isSet: true}
}

func (v NullableBulkImportResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkImportResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


